export const plans = [
    {
        id: "beijing-3-days",
        title: "北京经典 3 日路线",
        type: "travel",
        description: "故宫、天坛、颐和园串成一条轻重结合的北京入门路线。",
        days: ["故宫博物院", "天坛 + 城市散步", "颐和园 + 机动半天"],
        entries: [
            ["travel", "forbidden-city-palace-museum"],
            ["travel", "temple-of-heaven"],
            ["travel", "summer-palace"],
        ],
        tips: ["故宫务必提前预约", "天坛适合清晨去", "颐和园建议留半天以上"],
    },
    {
        id: "xian-luoyang-grottoes",
        title: "西安洛阳历史 4 日路线",
        type: "travel",
        description: "兵马俑和龙门石窟搭配, 更适合喜欢历史、博物馆和石窟艺术的人。",
        days: ["西安市区适应", "兵马俑", "高铁到洛阳", "龙门石窟 + 返程"],
        entries: [
            ["travel", "terracotta-army"],
            ["travel", "longmen-grottoes"],
        ],
        tips: ["兵马俑建议请讲解", "石窟类景点不要赶时间", "高铁衔接要留足余量"],
    },
    {
        id: "jiangnan-4-days",
        title: "江南园林古镇 4 日路线",
        type: "travel",
        description: "西湖、苏州园林、乌镇和西递宏村串联, 适合慢游和拍照。",
        days: ["杭州西湖", "苏州园林", "乌镇夜游", "西递宏村"],
        entries: [
            ["travel", "west-lake-hangzhou"],
            ["travel", "suzhou-classical-gardens"],
            ["travel", "wuzhen"],
            ["travel", "xidi-hongcun"],
        ],
        tips: ["古镇尽量住一晚", "园林适合上午慢看", "周末和节假日人流会明显增加"],
    },
    {
        id: "northwest-6-days",
        title: "西北风景人文 6 日路线",
        type: "travel",
        description: "敦煌、鸣沙山、青海湖和塔尔寺组合, 看沙漠、湖泊和宗教文化。",
        days: ["敦煌落地", "莫高窟", "鸣沙山月牙泉", "转场青海", "青海湖", "塔尔寺 + 西宁"],
        entries: [
            ["travel", "mogao-caves"],
            ["travel", "mingsha-mountain-crescent-spring"],
            ["travel", "qinghai-lake"],
            ["travel", "kumbum-monastery"],
        ],
        tips: ["西北转场距离长", "沙漠景点优先早晚", "高原地区注意休息"],
    },
    {
        id: "nolan-watch-order",
        title: "诺兰电影入门观看顺序",
        type: "movies",
        description: "从最容易进入的商业片开始, 再进入更复杂的时间和主题结构。",
        days: ["《盗梦空间》", "《星际穿越》", "《黑暗骑士》", "《奥本海默》", "《致命魔术》"],
        entries: [
            ["movies", "inception"],
            ["movies", "interstellar"],
            ["movies", "the-dark-knight"],
            ["movies", "oppenheimer"],
            ["movies", "the-prestige"],
        ],
        tips: ["先看类型快感强的片", "再回头看结构复杂度", "尽量完整观看, 不建议切碎看"],
    },
    {
        id: "pixar-family-list",
        title: "皮克斯和家庭动画片单",
        type: "movies",
        description: "适合周末、亲子和轻松补片, 但主题都有成人回味。",
        days: ["《玩具总动员》", "《机器人总动员》", "《飞屋环游记》", "《寻梦环游记》", "《头脑特工队2》"],
        entries: [
            ["movies", "toy-story"],
            ["movies", "wall-e"],
            ["movies", "up"],
            ["movies", "coco"],
            ["movies", "inside-out-2"],
        ],
        tips: ["亲子看可以先选更轻松的", "看完可以聊亲情、告别和成长", "动画不等于低龄"],
    },
    {
        id: "crime-tv-starter",
        title: "高分犯罪剧入门顺序",
        type: "tv",
        description: "从强情节到社会结构, 逐步进入更复杂的犯罪剧。",
        days: ["《绝命毒师》", "《风骚律师》", "《真探》", "《心灵猎人》", "《火线》"],
        entries: [
            ["tv", "breaking-bad"],
            ["tv", "better-call-saul"],
            ["tv", "true-detective"],
            ["tv", "mindhunter"],
            ["tv", "the-wire"],
        ],
        tips: ["先看强剧情更容易进入", "再看慢节奏社会剧", "不要倍速看人物对白"],
    },
    {
        id: "sci-fi-tv-route",
        title: "科幻悬疑剧观看路线",
        type: "tv",
        description: "从近未来寓言到时间循环和工作人格, 适合喜欢烧脑设定的人。",
        days: ["《黑镜》", "《暗黑》", "《人生切割术》", "《西部世界》", "《三体》"],
        entries: [
            ["tv", "black-mirror"],
            ["tv", "dark"],
            ["tv", "severance"],
            ["tv", "westworld"],
            ["tv", "three-body"],
        ],
        tips: ["每部剧设定密度都高", "建议看完一季再换", "适合配合专题和剧评复盘"],
    },
] as const;

export type Plan = (typeof plans)[number];
